name: web_terminal
description: "allasca (c) 2024"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  device_info_plus: ^9.1.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
