name: GH-Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install Dependencies
        run: flutter pub get
       # working-directory: ./example
      - name: Build Web
        run: flutter build web --release --source-maps
       # working-directory: ./example
      - name: Deploy
        run: |
          cd example/build/web
          git init
          git config user.name "allasca"
          git config user.email "y.allasca@gmail.com"
          git remote add secure-origin https://allasca:${github.token}@github.com/web_terminal.git
          git checkout -b gh-pages
          git add .
          git commit -m "Deployed Github Pages"
          git push --force secure-origin gh-pages
